### ISSUE TITLE
1.5.beta版本提示这个

### ISSUE THREAD

**Issue by Jasonvvei** [forkingdog/UITableView-FDTemplateLayoutCell#186]
[FDTemplateLayoutCell] Warning once only: Cannot get a proper cell height (now 0) from '- systemFittingSize:'(AutoLayout). You should check how constraints are built in cell, making it into 'self-sizing' cell.

**Comment by VVJason** [comment]
这？
![1c9a4960-eb63-4f8a-b3e3-9b8152928195](https://cloud.githubusercontent.com/assets/14148888/13870947/60cd294a-ed1b-11e5-8da2-d6f8c178fa37.png)

**Comment by sdkdimon** [comment]
Same issue, when use cells from xib (register programmatically).

**Comment by sdkdimon** [comment]
Issue appears when UITableView width for some reason is equals to zero.
In my case the reason was that i am create UITableView in programmatically way.
My solution is to check UITableView width in heightForRowAtIndexPath method and if it is grater than zero then make calculations by fd_heightForCellWithIdentifier method, otherwise return always zero.
```
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    CGFloat tableViewWidth = [tableView frame].size.width;
    CGFloat rowHeight = .0f;
    if (tableViewWidth > 0){
        rowHeight = [tableView fd_heightForCellWithIdentifier:_cellReuseId cacheByIndexPath:indexPath configuration:^(id cell) {
            [self configureCell:cell atIndex:[indexPath row]];
        }];
    }
    return rowHeight;
}
```

**Comment by weekwood** [comment]
@Jasonvvei make sure you enable Self-sizing and add constraints
