### ISSUE TITLE
Why explicitly call systemLayoutSizeFittingSize

### ISSUE THREAD

**Issue by liuxuan30** [forkingdog/UITableView-FDTemplateLayoutCell#3]
I remember the auto layout engine will calculate the frame based on the constraints, why you explicitly call systemLayoutSizeFittingSize?

I tried to delete the delegate and it turned out the imageView's constraint is still the same, but the height is half of the height constraint, and the image itself size is not fully occupied, so I am thinking, will this be a bug for your imageView not correctly set? 

For exmaple, in the phil cell with the beauty's image, size is 160,97, while constraint is 160,195 and alignment rect is 160,195 as well. 
If set the delegate, the size is 160,195, constraint 160,195, alignment rect 160,195.

![imagesize](https://cloud.githubusercontent.com/assets/4375169/7266448/50a79b70-e8dc-11e4-920d-73973408da9f.png)

**Comment by sunnyxx** [comment]
Content mode of the image view in demo is "Aspect Fit",  When its frame goes smaller than image's size, image will fit (scale) aspect (aspect ratio) its intrinsic content size. If you delete "-tableView:heightForRowAtIndexPath:" method, table view will take the default "row height" (height of prototype cell in Interface Builder)

**Comment by liuxuan30** [comment]
the intrinsic size is not changed, as well as the constraints. I am curious why I don't see the engine reports cannot satisfy constraint XXX...
the constraint is (160,195） while the imageView frame size is （160,97）. 97*2=195. 
```
(lldb) po 0x7fb0c15a6290
<UIImageView: 0x7fb0c15a6290; frame = (16 60.5; 160 97); opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x7fb0c15a6170>>

(lldb) po [0x7fb0c15a6290 constraints]
<__NSArrayM 0x7fb0c383aa20>(
<NSContentSizeLayoutConstraint:0x7fb0c380b960 H:[UIImageView:0x7fb0c15a6290(160)] Hug:251 CompressionResistance:750>,
<NSContentSizeLayoutConstraint:0x7fb0c380c3e0 V:[UIImageView:0x7fb0c15a6290(195)] Hug:251 CompressionResistance:750>
)
```

**Comment by sunnyxx** [comment]
I don't quite understand your question, maybe you should google the differences between UIViewContentMode and Layout Constraints, which may not be what you think. I'm gonna close this issue.

**Comment by liuxuan30** [comment]
Well it is not quite an issue, but it is a bug that confuses people. You have constraints saying the height needs to be 195 while the actual frame height is just 97, half of 195. Don't you see the problem?

**Comment by sunnyxx** [comment]
This is not a "problem", it's how intrinsic layout constraint works. I didn't add any width or height constraint to the image view, Auto Layout Engine added it at runtime by image's intrinsic content size, which you had seen:
```
(lldb) po [0x7fb0c15a6290 constraints]
<__NSArrayM 0x7fb0c383aa20>(
<NSContentSizeLayoutConstraint:0x7fb0c380b960 H:[UIImageView:0x7fb0c15a6290(160)] Hug:251 CompressionResistance:750>,
<NSContentSizeLayoutConstraint:0x7fb0c380c3e0 V:[UIImageView:0x7fb0c15a6290(195)] Hug:251 CompressionResistance:750>
)
```
And `NSContentSizeLayoutConstraint` is a private class which you may google it for some results, like:  http://www.raywenderlich.com/forums/viewtopic.php?f=2&t=5222

Why won't it complain when height(195) is not satisfied? Because this image view's `Content Compression Resistance Priority` is 750 by default, which means it can be compressed when other constraints are "stronger" than it. So this constraint: 
```
<NSContentSizeLayoutConstraint:0x7fb0c380c3e0 V:[UIImageView:0x7fb0c15a6290(195)] Hug:251 CompressionResistance:750>
```
DOES NOT WORK, ignored by Auto Layout Engine. You may try to set this priority to `1000` to see what is gonna happen.  

After compressed by other constraints, it's frame is smaller than intrinsic content size, and finally, UIViewContentMode does its job.

**Comment by liuxuan30** [comment]
Good catch! helps clean my mind, thanks!
