### ISSUE TITLE
it doesn't work when content contains dynamic image view

### ISSUE THREAD

**Issue by caofei10119** [forkingdog/UITableView-FDTemplateLayoutCell#37]
I have one image view inside cell content that loads photo from server.
image view content mode is aspect fill and only width has been defined using autolayout in storyboard.
height should be increased dynamically based on loaded photo size.
constraints for cell content view has been already self-satisfied.
what am I missing?

**Comment by caofei10119** [comment]
any thought?

**Comment by sunnyxx** [comment]
If only width constraint has been set, auto layout engine cannot calculate out a right height for there are not enough informations to determine image view's intrinsic content size (aspect fill mode is not a constraint)

**Comment by caofei10119** [comment]
so what is a solution? height constraint should be applied?

**Comment by sunnyxx** [comment]
Yes, that's not avoidable.

**Comment by caofei10119** [comment]
then all the images inside cell should have static height?

**Comment by sunnyxx** [comment]
Image views in FDTemplateLayoutCell's demo don't have a width or height constraint because they are using local images, which image sizes are fixed, and will be translated to intrinsic content size constraints. However,  your images are downloaded from server and don't know actual sizes before that, so you may try one of:  
- don't load your cells until all images done.
- put a placeholder image and reload using real image.
- add both width and height constraints, IBOutlet them, set their constant value by real image sizes.   

This is a problem no matter whether you use FDTemplateLayoutCell's or not. The best solution is getting image's size **at same time** when you get image's url.

**Comment by caofei10119** [comment]
suppose we know the width and height when get image url, where should width and height constraint constant be changed?

**Comment by sunnyxx** [comment]
IBOutlet width and height constraints, reset their constant value when you configure cells, maybe look like:  
``` objc
// In your cell
- (void)setEntity:(YourEntity *)entity {
    self.imageViewWidthConstraint.constant = entity.imageSize.width;
    self.imageViewHeightConstraint.constant = entity.imageSize.height;
}
```

**Comment by caofei10119** [comment]
thanks
