### ISSUE TITLE
uilabel in cell,you set hard width constraint,if use preferredMaxLayoutWidth

### ISSUE THREAD

**Issue by kuanglijun312** [forkingdog/UITableView-FDTemplateLayoutCell#4]
// Add a hard width constraint to make dynamic content views (like labels) expand vertically instead
    // of growing horizontally, in a flow-layout manner.

It is good idea, but if i use preferredMaxLayoutWidth for uilabel,width constraint is not essential,is that right?

ps:  before using systemLayoutSizeFittingSize, setNeedsLayout() and layoutIfNeeded() is not need call?

**Comment by philcn** [comment]
yep that's right, except for you'll have to mix up manual frame calculation (in order to get desired `preferredMaxLayoutWidth` value) with auto layout constraints, which makes the view harder to maintain.

`systemLayoutSizeFittingSize` is an independent method that calculates an UIView's frame using auto layout without being aware of its superview context, thus is preferred over `layoutIfNeeded`.

**Comment by kuanglijun312** [comment]
OK,thank you~!
